/*
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'package:{{project_name}}/config/flavor_config.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        switch (FlavorConfig.instance.buildFlavor) {
// @REPEAT_FLAVOR_START
          case BuildFlavors.{{flavor}}:
            return android{{flavor}};
// @REPEAT_FLAVOR_END
        }
      case TargetPlatform.iOS:
        switch (FlavorConfig.instance.buildFlavor) {
// @REPEAT_FLAVOR_START
          case BuildFlavors.{{flavor}}:
            return ios{{flavor}};
// @REPEAT_FLAVOR_END
        }
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

// @REPEAT_FLAVOR_START
  static const FirebaseOptions android{{flavor}} = FirebaseOptions(
    apiKey: '{{android_api_key_{{flavor}}}}',
    appId: '{{android_app_id_{{flavor}}}}',
    messagingSenderId: '{{messaging_sender_id_{{flavor}}}}',
    projectId: '{{project_id_{{flavor}}}}',
    storageBucket: '{{storage_bucket_{{flavor}}}}',
  );

  static const FirebaseOptions ios{{flavor}} = FirebaseOptions(
    apiKey: '{{ios_api_key_{{flavor}}}}',
    appId: '{{ios_app_id_{{flavor}}}}',
    messagingSenderId: '{{messaging_sender_id_{{flavor}}}}',
    projectId: '{{project_id_{{flavor}}}}',
    storageBucket: '{{storage_bucket_{{flavor}}}}',
    iosBundleId: '{{ios_bundle_id_{{flavor}}}}',
  );
// @REPEAT_FLAVOR_END
}
*/
